### PR TITLE
fix field clashes with 'file' in Django 1.9

### PR DESCRIPTION
**Pull request by stefanfoulis**
Set cmsplugin_ptr and remove related_name to avoid field name clashes
with any other plugin that has a field called "file".

see https://github.com/divio/django-cms/issues/5030

### CODE REVIEW

**Comment by mkoistinen** [comment]
:+1:

**Comment by stefanfoulis** [comment]
@mkoistinen @yakky since the rename from ``file`` to ``source`` has not been released yet: what do you think about reverting that. Removing the reverse relation should not make that change necessary anymore.

**Comment by yakky** [comment]
@stefanfoulis +1

**Comment by stefanfoulis** [comment]
@yakky ok. I'll remove those commits

**Pull request merged**
